version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: Gosemadc/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      env_file: ./server/config/${ENV}.env
    ports:
      - 27017:27017

mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - Gosemadc-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local